### ISSUE TITLE
Text editor not responding to backspace/space

### ISSUE THREAD

**Issue by fredbeast** [vjrantal/badge-builder#126]
Bug on Chrome (Windows 10) where text input struggles a bit:

- Space bar double-tap reverts cursor to beginning of line

- Space bar only fires when cursor is not at the end of the line 
 
- Backspace not working, have to use Delete as an alternative

Here's what I mean... (!):
https://drive.google.com/file/d/0BxZ-5bz5B_I5NG1HMUxaQ3kzWFU/view

**Comment by vjrantal** [comment]
I have noticed same (or similar) behavior on other browsers as well and it can be also reproduce in the WYSIWYG component demo page https://miztroh.github.io/bower_components/wysiwyg-e/ (which means we are most likely not breaking it in our code).

@liliankasem, @deadlyfingers, @fredbeast: I think our options are either to look for a better WYSIWYG editor or alternatively allow users to author the HTML content in some other (external) editor and just paste in the generated HTML.

**Comment by deadlyfingers** [comment]
@vjrantal we might remove this in favour of simple textbox to paste in preformatted HTML content. (The HTML entities could then be encoded/decoded for edit or preview mode)

**Comment by deadlyfingers** [comment]
Now updated: https://github.com/vjrantal/badge-builder/pull/128
