### ISSUE TITLE
Create / edit page design

### ISSUE THREAD

**Issue by deadlyfingers** [vjrantal/badge-builder#36]
This needs some design polish.
- Save button needs to be obvious - move to nav bar?
- FAB buttons need labels or better icons
- Move create buttons to Sidebar?
- New elements should have clear division (each should be in it's own row card)

**Comment by deadlyfingers** [comment]
Edit buttons should be positioned so the mouse doesn't have to move from one side of screen to the other. 
- The new layout should be optimised for efficiency of movement

**Comment by vjrantal** [comment]
Low priority note: If you get rid of the header bar or the custom condensing transformation that is there now, please remove code related to that from app.js. Just so that we don't leave unused code behind.

**Comment by deadlyfingers** [comment]
Yes that will have to go - also I think it doesn't work well when scrolling with drag and drop elements. Auto-scrolling down the ways works, but dragging elements up doesn't autoscroll - I'll venture  its all that condensing header scrolling trickery getting in the way.
