### ISSUE TITLE
Answer checking bug

### ISSUE THREAD

**Issue by deadlyfingers** [vjrantal/badge-builder#96]
Bug needs fixed: `TypeError: Cannot read property 'toLowerCase' of undefined 
helpers.js:51`

**Comment by deadlyfingers** [comment]
Recreate steps: create a quiz with multiple sections and text-input quiz elements.

**Comment by deadlyfingers** [comment]
If we check only against the page answers then the 'undefined' checks will not be needed. 
https://github.com/vjrantal/badge-builder/blob/5625b542724d25d96f193e7d0b2895483604bbd8/server/routes/helpers.js#L19
@vjrantal @liliankasem thoughts?

**Comment by deadlyfingers** [comment]
Got a quick fix in for now with an **undefined** check on **userAnswer**
-  `var userAnswer = answers[id];`

**Comment by deadlyfingers** [comment]
@liliankasem I had to fix this quickly as it was blocking the new drag and drop element. The quick fix I mentioned will be in next PR.

**Comment by liliankasem** [comment]
Cool, that's fine :)
